apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  labels:
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: logging-gitops
  annotations:
    openshift.io/display-name: Red Hat Logging
