# From setup-keycloak-namespace.sh:
#   oc create namespace <NAMESPACE>
#   oc label namespace <NAMESPACE> purpose=Keycloak
#   oc annotate namespace <NAMESPACE> openshift.io/description="Namespace to host Keycloak services"
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  labels:
    purpose: Keycloak
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    openshift.io/description: Namespace to host Keycloak services
