apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  labels:
    purpose: Keycloak
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    openshift.io/description: Namespace to host Keycloak services
    openshift.io/display-name: Keycloak
