apiVersion: v1
kind: Namespace
metadata:
  name: crunchy-operator
  labels:
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    openshift.io/display-name: Crunchy Postgres Operator
