apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-postgres
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  project: appkeycloak
  source:
    path: keycloak/crunchy/instance/overlays/lab
    repoURL: https://github.com/ebeaudoi/ocp-ansible-deployment.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
