apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - git-repository-secret.yaml
  - appkeycloak-project.yaml
  - crunchy-operator-app-argo.yaml
  - rhbk-operator-app-argo.yaml
  - crunchy-instance-app-argo.yaml
  - keycloak-instance-app-argo.yaml
