apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Must match Keycloak namespace so Crunchy creates
# Secret keycloak-postgres-pguser-keycloak where Keycloak can read it.
namespace: keycloak

resources:
  - ../../base

patches:
  - path: postgrescluster-patch.yaml
    target:
      group: postgres-operator.crunchydata.com
      version: v1beta1
      kind: PostgresCluster
      name: keycloak-postgres
