apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coo
  namespace: logging-gitops
spec:
  destination:
    namespace: openshift-cluster-observability-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: logging/coo/base
    repoURL: https://github.com/ebeaudoi/ocp-ansible-deployment.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
