apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - applogging-project.yaml
  - loggingoperator-app-argo.yaml
  - lokioperator-app-argo.yaml
  - loki-instance-app-argo.yaml
  - coo-app-argo.yaml
  - logginginstance-app-argo.yaml
