apiVersion: v1
kind: Namespace
metadata:
  name: logging-gitops
---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: logging-gitops
  namespace: logging-gitops
spec:
  server:
    route:
      enabled: true
  rbac:
    defaultPolicy: ''
    policy: |
      g, system:cluster-admins, role:admin
    scopes: '[groups]'
