apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lokioperator
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: loki/base
    repoURL: ssh://git@gitlab.devu.ca:2289/a-McLaughlin.J/logging.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
