apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-instance
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: loki/instance
    repoURL: git@github.com:ebeaudoi/ocp-ansible-deployment.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
