apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: sso
    purpose: Keycloak
spec:
  additionalOptions:
    - name: metrics-enabled
      value: "true"
  db:
    vendor: postgres
    url: jdbc:postgresql://keycloak-postgres-primary.keycloak.svc:5432/keycloak?currentSchema=public&sslmode=require
    usernameSecret:
      name: keycloak-postgres-pguser-keycloak
      key: user
    passwordSecret:
      name: keycloak-postgres-pguser-keycloak
      key: password
  hostname:
    # Overridden in overlays/lab/keycloak-patch.yaml
    hostname: keycloak.apps.example.com
  http:
    tlsSecret: keycloak-tls-secret
  instances: 1
  ingress:
    enabled: true
