apiVersion: v1
data:
  service-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6DCCA9CgAwIBAgITagAAA4HtRTn5SdJG8wAAAAADgTANBgkqhkiG9w0BAQsF
    ADBDMRIwEAYKCZImiZPyLGQBGRYCY2ExFDASBgoJkiaJk/IsZAEZFgRkZXZ1MRcw
    FQYDVQQDEw5UREwgSXNzdWluZyBDQTAeFw0yNjA0MjkxNDA1NDJaFw0yODA0Mjgx
    NDA1NDJaMGAxCzAJBgNVBAYTAkNBMQswCQYDVQQIEwJPTjEPMA0GA1UEBxMGT3R0
    YXdhMQwwCgYDVQQKEwNETkQxDDAKBgNVBAsTA1RETDEXMBUGA1UEAxMOYWlzdG9y
    LmRldnUuY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC3z9+PD+FS
    Re2Gvy8ECaHZFgsjAqIs0jyB4Zp6g4uLAaBaWJw7TcCJ6XVMoNZb2FhZc+VYGey4
    dzBRokwVTE6J1x/mrlfrDwdGeJZFL1dDae2+a87CxZtvb1S5QQcQv3NrVpwDMAGL
    idk0E59f8gO/hHtcoS8h/neQkHyy74hojRwg6ByXIxIjZ6Y+F2thMH1bdF/ogNNl
    A8PQdev3lXmiwDlrldumYLZdc2ePi5hE0FKZcWir60duKPJOcM/ZTl4/r67W48eM
    E1XKWVsd0EXxvCYtVoTH4scHAl2ChupD+We37RZCrUGp0Tse35zSQYsGZGqRCdsA
    2YkSit0lz4fJAgMBAAGjggG2MIIBsjAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAww
    CgYIKwYBBQUHAwEwRwYDVR0RBEAwPoIfYWlzdG9yLWNvbnNvbGUuYXBwcy5vczQu
    ZGV2dS5jYYIbYWlzdG9yLWFwaS5hcHBzLm9zNC5kZXZ1LmNhMB0GA1UdDgQWBBS2
    zOB7NM3ZVieCm8oxyo30tpsilTAfBgNVHSMEGDAWgBTMHbJUDhgg+uUZC5Ytruu5
    E0iVjjA+BgNVHR8ENzA1MDOgMaAvhi1odHRwOi8vY3JsLmRldnUuY2EvcGtpL1RE
    TCUyMElzc3VpbmclMjBDQS5jcmwwZwYIKwYBBQUHAQEEWzBZMFcGCCsGAQUFBzAC
    hktodHRwOi8vY3JsLmRldnUuY2EvcGtpL0RFVi1UVU4tU1VCT1JESU5BVEVDQS5k
    ZXZ1LmNhX1RETCUyMElzc3VpbmclMjBDQS5jcnQwPAYJKwYBBAGCNxUHBC8wLQYl
    KwYBBAGCNxUIhPHUCKm8XIXFlQSDuIplgpS4Si6Hlu0MhpDfRAIBZAIBEjAbBgkr
    BgEEAYI3FQoEDjAMMAoGCCsGAQUFBwMBMA0GCSqGSIb3DQEBCwUAA4IBAQBn8QbT
    0C6eYCRM2KRCWmobKJDqU+AGOIBokkhnKrwRLY5JakNzvnB3XrQy8kqPhcegB5qD
    2zhYgT+3qqAgBGEAJM17/Zm+EyndBt0Ng3gNQ/pY+c3A3XhYp5e0sDRXLbUtFxkJ
    XI3MhOYFMmeue9U6v3VYAebU4pckGODhVSBK37SW+bTzmx7omYiywXVCQd2G/NxQ
    JDcI0Cf7ytn+7FqaPwrMR7wwbvgLCddNNSrSZ9Oymk/ZU16QkKNLGcH2Ior+sfwx
    5lgUTUyZhEnX6AVohnvo2EpFCyMOvT0QkAdQLOVlEoAvAvIvFiIGKwpejLZ3os3R
    ouECM6z3WGUVvc6d
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: loki-s3-ca-bundle
  namespace: openshift-logging
