apiVersion: v1
data:
  service-ca.crt: |
-----BEGIN CERTIFICATE-----
MIIGwjCCBKqgAwIBAgIRAIrmVnxyFT3fQyKdzWRlVfswDQYJKoZIhvcNAQELBQAw
TTEQMA4GA1UEChMHUmVkIEhhdDENMAsGA1UECxMEcHJvZDEqMCgGA1UEAxMhMjAy
MyBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgUkhDU3YyMB4XDTI2MDkyNDE5NTExOVoX
DTI3MDkxOTE5NTExOVowgcAxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBD
YXJvbGluYTEQMA4GA1UEBwwHUmFsZWlnaDEQMA4GA1UECgwHUmVkIEhhdDEfMB0G
A1UECwwWSW5mb3JtYXRpb24gVGVjaG5vbG9neTEiMCAGCSqGSIb3DQEJARYTZWJl
YXVkb2lAcmVkaGF0LmNvbTEvMC0GA1UEAwwmb2NwcmQzLmViZWF1ZG9pLnRhbWxh
Yi5yZHUyLnJlZGhhdC5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC
AQDSxVM8JrWUWfERR4bis4D2bAzr4xjtf4USULvMYJeCQmEZW7GIuX3+/k1Smto6
l7atp7rxOChAWoCvhXApPOEl28s2aoq0c7QwV41AO9Cq8wGMVONQMW661kR5mIA1
ppS2Md9ycoWyIbpgxToIxi3EacUya+oMrDDQ5jP6CHNCerJAZrJAf96qYqVTKISt
Dc/FubYjzdfPXYUp+7idc/dEB/Hy4NnxBCn67Q9Vq+fbM0xPdkZnbXINCrVikPsT
WqowwO4N9HINDcBMe96hwWZ3bN4AKrpvn3yxvupAQlaoNGQPcrCoRPxJ/AXBz9Iu
veVcy298Oqg3RQoAJ9BU9mLj0+PyBexpbL55WhP3e6YHQbys8ESIckWc+ib4OHqk
aLwOCi9sZtS3vDiuzyEfaBONuEKNXQFOy78pc5FbLmrRmdlcY6+KQDQsbVIv8a28
n8Az0OTzKruqExqU3snLD9bCpdGA5GX8yv8tJAKFX1+hDSyGF8ydHsAGwrLk4ww3
PV8Rzi4+tf5AschP4WPEkR89Pb98HYSgV7PkScFICi2WS8VwCs+bqtIunc7J+sSA
NytnG+NEvKM7CkuY7/so2rtbDPZ4g4kET9evkt/xp4kvKLlwmtc1M22QQYZ9yqi8
AqyaEbj6At6g7uehFCUQchprj4IR9SkU1YHfwQm4SkxGJwIDAQABo4IBJzCCASMw
HwYDVR0jBBgwFoAUB06LyZHBWtk7DBRpmQ/qhyCWhfowQAYIKwYBBQUHAQEENDAy
MDAGCCsGAQUFBzABhiRodHRwOi8vb2NzcC5jb3JwLnJlZGhhdC5jb20vY2Evb2Nz
cC8wDgYDVR0PAQH/BAQDAgTwMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
AjCBjgYDVR0RBIGGMIGDgiZvY3ByZDMuZWJlYXVkb2kudGFtbGFiLnJkdTIucmVk
aGF0LmNvbYItKi5hcHBzLm9jcHJkMy5lYmVhdWRvaS50YW1sYWIucmR1Mi5yZWRo
YXQuY29tgiphcGkub2NwcmQzLmViZWF1ZG9pLnRhbWxhYi5yZHUyLnJlZGhhdC5j
b20wDQYJKoZIhvcNAQELBQADggIBADergkczEoNMK1q72cxoZeWksEkm6vkiKiw7
UW+i24Km0RigfThKZcVniRLbuLM7JV2cY/PYsaaSJgvU/qCccdsiodlTzmwoRnfJ
JgKiKKGii4LTVfaQpvcyaR3EzX4KlcPoxd6S4WwtHjbPYZM8mS0BsiYuF24Us2rl
sd5B+IuzDJNpjOOlOw2YpZSG1nyQNlcP9SOsR7VSq/c7aA/9B7S+y02eWdKroMdV
mTeB0beRe8dKEpfC4OsIFQk7w6fg8GSyn0l6Fce/3NRW8p6i4HTgneHRI+IzMEGo
P+5luizfb4gx0bKuw5APb3SwTcaCwjSvBXV6VVTeA6UpzkY+INpLkyejDPgz6AoL
98iKCGNPgaybi5Qu3MkxS5gZnH/ZBISf6hlxrpT0/4mc1v4Dk1239fCCPzFaX5GX
+CAnqvLIZZQYK5FOiuMRJfyuOVFjlaHo0Xwu+lZ1jjKqwiAikvLCtgBbFpKa4Vgn
bG4XridoRREE0m+aYrCEEJBDz4cBpgSjE3IOkxSHlqAeL2FagRmUz67d16eT/HVS
zQeL4y3yz0lzmMJrXCli7o6Z5yJEn1jgjjVGG1PEFXtdgcpnBy3KKwaWe3RJyz8t
z8wGwG+z5TfKDR6is7bhlzHBSiofJCMDlu3xijMvtnN+LDfkSKi1lvbXcI9LLH9W
FjewD5hf
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIF6TCCA9GgAwIBAgIFICIEEF4wDQYJKoZIhvcNAQEMBQAwgaMxCzAJBgNVBAYT
AlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4GA1UEBwwHUmFsZWlnaDEW
MBQGA1UECgwNUmVkIEhhdCwgSW5jLjETMBEGA1UECwwKUmVkIEhhdCBJVDEZMBcG
A1UEAwwQSW50ZXJuYWwgUm9vdCBDQTEhMB8GCSqGSIb3DQEJARYSaW5mb3NlY0By
ZWRoYXQuY29tMB4XDTIzMDQwNjE4MjI0M1oXDTQzMDQwMjE4MjI0M1owTTEQMA4G
A1UEChMHUmVkIEhhdDENMAsGA1UECxMEcHJvZDEqMCgGA1UEAxMhMjAyMyBDZXJ0
aWZpY2F0ZSBBdXRob3JpdHkgUkhDU3YyMIICIjANBgkqhkiG9w0BAQEFAAOCAg8A
MIICCgKCAgEAukugmlnSPsZbxx3MTj+mwB7bkppCtk7ch9ggh+47gWQsMALO1CG8
BNUlWBJWNnK5qtufMPXrKk6X06akpo4NDCzVR8Wqs/NltIR+o9R0+4rum/M9Nxa5
oMk8Xgj5h/SyDu8x02NBJeiZV1E5oxVJjqb33AcoHGkVO3O3fPW0qNyYCsm9rWXW
WJ2snjC9Nb9WYUMhRrsGPzUUGmRgLruET2lQOGIYqbwnyG5E6ajnDypbhxhIykyv
vwtJMQ1Y+jBxA48ZI5pRPS/c4rWyl1i/7gftiJVk8QxpGYd6+Thi2q9sadK9JWYJ
eWgvZwMuYO0eC12TDS4sKqmok9eZ9EIhuS1/Yuf2sodUBfwp9Sm/L6BzN/6kjADR
+Sv9Dl2TTYLlVNGWhtiWZCNGZ+I/808KanLtqC7uJX8pr7DIErvo+RGqc8TVfCYo
eu1Aj2mRBnn1s4ZYwnxR5JtDAIhRSiv6VjWe7aS6cBywvkffT5pUzR+XQUxzYHmv
RWFRZrXQJdZBJzq4d71bUwE3DVTODSJqc+LB6mcDNOPDtm9kVNyGewMMBz6cjhdq
UV4t9DrFed5YELm8J+tfc/hJE+8w0waBW8f6dYAE3aIikr/k+XqxW4mm+4sTJ+UR
2U+ts9ipOZNPVrv9Mriw/S3rq+sMRqjI9pU9T7oVfS5AgfDUVuan588CAwEAAaN5
MHcwHQYDVR0OBBYEFAdOi8mRwVrZOwwUaZkP6ocgloX6MB8GA1UdIwQYMBaAFLX6
jeUKeKEJldtNIYaVallPSciLMBIGA1UdEwEB/wQIMAYBAf8CAQEwDgYDVR0PAQH/
BAQDAgGGMBEGCWCGSAGG+EIBAQQEAwIBBjANBgkqhkiG9w0BAQwFAAOCAgEAQQxq
wobjk1YHzCy5faItBt6Q9PwEV7vtYTWIUoOLVCU7XNw/397YPWw7MtzBIDocwYY6
wChlmcrj3IFDb12gGW/bU761f6QdWbhHIBkxaK+s2S14wNvTRk3cT9Sm+wBCcnb/
ncE0bPpLyfFxe80+PaIdk0Cy2uGrk+53Ute0fPQJtP93dn2kZK8Iobg1A6Mj+MOM
qAouQ/7ZcOHvkmfAEonYPc9ERGd6uTwRVfHWfncRbqBkiiK8CHH6nEx7tpI2vP4Z
GcKRM6htMdW/PUJ3fcss+12SXBWWvkniVnQv9xl7E12uKni1VF9XthCflz9BrM5L
/fCidOyAdYSe8yjgYOyDWjgsTb2R/nbmmS2NNVagnK6XP0nqQHnQPSjhh27W/QnN
ob9H5CfiZe62l5o/7aMaEQqXaAmU8hqxPDo4RpduVR/mUWlQd2n4XWxKvSgMLCUR
YanJeYbNI/S1ie7CCOdSDedcrAUc3LC7LOGj/8901qlUt19eiUA4Z3h5CTaaXmd+
8p5sPP4CPmUw+BtvEupLYhJ3MpWm8J7VBdHMi9bxOq5OCfJgArN39nXoM1CDBc73
QL5ldqlwCXC/V4rOCKgcHuDg9vt6DDm3itRWHHjqAWZDMGzoCuZ/8PONWtHLqQjR
hsOZNhLn4WtaIBdt98nhjIL/ymLVhv1b5VZESTA=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIF6TCCA9GgAwIBAgIFICIEEF4wDQYJKoZIhvcNAQEMBQAwgaMxCzAJBgNVBAYT
AlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4GA1UEBwwHUmFsZWlnaDEW
MBQGA1UECgwNUmVkIEhhdCwgSW5jLjETMBEGA1UECwwKUmVkIEhhdCBJVDEZMBcG
A1UEAwwQSW50ZXJuYWwgUm9vdCBDQTEhMB8GCSqGSIb3DQEJARYSaW5mb3NlY0By
ZWRoYXQuY29tMB4XDTIzMDQwNjE4MjI0M1oXDTQzMDQwMjE4MjI0M1owTTEQMA4G
A1UEChMHUmVkIEhhdDENMAsGA1UECxMEcHJvZDEqMCgGA1UEAxMhMjAyMyBDZXJ0
aWZpY2F0ZSBBdXRob3JpdHkgUkhDU3YyMIICIjANBgkqhkiG9w0BAQEFAAOCAg8A
MIICCgKCAgEAukugmlnSPsZbxx3MTj+mwB7bkppCtk7ch9ggh+47gWQsMALO1CG8
BNUlWBJWNnK5qtufMPXrKk6X06akpo4NDCzVR8Wqs/NltIR+o9R0+4rum/M9Nxa5
oMk8Xgj5h/SyDu8x02NBJeiZV1E5oxVJjqb33AcoHGkVO3O3fPW0qNyYCsm9rWXW
WJ2snjC9Nb9WYUMhRrsGPzUUGmRgLruET2lQOGIYqbwnyG5E6ajnDypbhxhIykyv
vwtJMQ1Y+jBxA48ZI5pRPS/c4rWyl1i/7gftiJVk8QxpGYd6+Thi2q9sadK9JWYJ
eWgvZwMuYO0eC12TDS4sKqmok9eZ9EIhuS1/Yuf2sodUBfwp9Sm/L6BzN/6kjADR
+Sv9Dl2TTYLlVNGWhtiWZCNGZ+I/808KanLtqC7uJX8pr7DIErvo+RGqc8TVfCYo
eu1Aj2mRBnn1s4ZYwnxR5JtDAIhRSiv6VjWe7aS6cBywvkffT5pUzR+XQUxzYHmv
RWFRZrXQJdZBJzq4d71bUwE3DVTODSJqc+LB6mcDNOPDtm9kVNyGewMMBz6cjhdq
UV4t9DrFed5YELm8J+tfc/hJE+8w0waBW8f6dYAE3aIikr/k+XqxW4mm+4sTJ+UR
2U+ts9ipOZNPVrv9Mriw/S3rq+sMRqjI9pU9T7oVfS5AgfDUVuan588CAwEAAaN5
MHcwHQYDVR0OBBYEFAdOi8mRwVrZOwwUaZkP6ocgloX6MB8GA1UdIwQYMBaAFLX6
jeUKeKEJldtNIYaVallPSciLMBIGA1UdEwEB/wQIMAYBAf8CAQEwDgYDVR0PAQH/
BAQDAgGGMBEGCWCGSAGG+EIBAQQEAwIBBjANBgkqhkiG9w0BAQwFAAOCAgEAQQxq
wobjk1YHzCy5faItBt6Q9PwEV7vtYTWIUoOLVCU7XNw/397YPWw7MtzBIDocwYY6
wChlmcrj3IFDb12gGW/bU761f6QdWbhHIBkxaK+s2S14wNvTRk3cT9Sm+wBCcnb/
ncE0bPpLyfFxe80+PaIdk0Cy2uGrk+53Ute0fPQJtP93dn2kZK8Iobg1A6Mj+MOM
qAouQ/7ZcOHvkmfAEonYPc9ERGd6uTwRVfHWfncRbqBkiiK8CHH6nEx7tpI2vP4Z
GcKRM6htMdW/PUJ3fcss+12SXBWWvkniVnQv9xl7E12uKni1VF9XthCflz9BrM5L
/fCidOyAdYSe8yjgYOyDWjgsTb2R/nbmmS2NNVagnK6XP0nqQHnQPSjhh27W/QnN
ob9H5CfiZe62l5o/7aMaEQqXaAmU8hqxPDo4RpduVR/mUWlQd2n4XWxKvSgMLCUR
YanJeYbNI/S1ie7CCOdSDedcrAUc3LC7LOGj/8901qlUt19eiUA4Z3h5CTaaXmd+
8p5sPP4CPmUw+BtvEupLYhJ3MpWm8J7VBdHMi9bxOq5OCfJgArN39nXoM1CDBc73
QL5ldqlwCXC/V4rOCKgcHuDg9vt6DDm3itRWHHjqAWZDMGzoCuZ/8PONWtHLqQjR
hsOZNhLn4WtaIBdt98nhjIL/ymLVhv1b5VZESTA=
-----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: loki-s3-ca-bundle
  namespace: openshift-logging
