apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coo-uiplugin-patcher
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  # create cannot be restricted by resourceNames
  - apiGroups: ["observability.openshift.io"]
    resources: ["uiplugins"]
    verbs: ["create", "delete", "get", "list", "watch", "patch", "update"]
