apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Change this to your lab Keycloak namespace name
namespace: keycloak

resources:
  - ../../base

patches:
  - path: namespace-patch.yaml
    target:
      version: v1
      kind: Namespace
      name: keycloak
